MyBlog.Web/Areas/Admin/Controllers/PostsController.cs
namespace MyBlog.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Identity;
    using MyBlog.Models;
    using MyBlog.Common.BindingModels;
    using MyBlog.Services.Contracts;
    using System.Threading.Tasks;
    using MyBlog.Web.Infrastructure.Extensions;

    public class PostsController : AdminController
    {
        private readonly IPostService posts;
        private readonly UserManager<User> userManager;
        private readonly ICategoryService categories;

        public PostsController(IPostService posts,
                               UserManager<User> userManager,
                               ICategoryService categories)
        {
            this.posts = posts;
            this.userManager = userManager;
            this.categories = categories;
        }

        public IActionResult Create()
        {
            var model = new PostBindingModel
            {
                Categories = this.categories.All()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PostBindingModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!ModelState.IsValid)
            {
                model.Categories = this.categories.All();

                return View(model);
            }

            if (posts.Exists(model.Title))
            {
                this.ModelState.AddModelError("", $"Post {model.Title} already exists!");

                model.Categories = this.categories.All();

                return View(model);
            }

            var postId = await this.posts.CreateAsync(model.Title, model.Content, model.Category, userId);

            return RedirectToPage("/Posts/Details", new { id = postId });
        }

        public IActionResult Edit(int id)
        {
            var post = this.posts.ById(id);

            if (post == null)
            {
                return NotFound();
            }

            post.Categories = categories.All();

            return View(post);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, PostBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = categories.All();

                return View(model);
            }

            if (posts.Exists(model.Title))
            {
                this.ModelState.AddModelError("", $"Post {model.Title} already exists!");
            }

            await this.posts.EditAsync(id, model);

            this.TempData.AddSuccessMessage(string.Format(WebConstants.EdittedMessage, "Post"));

            return Redirect("/");
        }

        public IActionResult Delete(int id)
        {
            var post = this.posts.ById(id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, PostBindingModel model)
        {
            await this.posts.DeleteAsync(id);

            this.TempData.AddSuccessMessage(string.Format(WebConstants.DeletedMessage, "Post"));

            return Redirect("/");
        }
    }
}

MyBlog.Web/Controllers/CommentsController.cs
namespace MyBlog.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using MyBlog.Common.BindingModels;
    using MyBlog.Models;
    using MyBlog.Services.Contracts;
    using MyBlog.Web.Infrastructure.Extensions;
    using System.Threading.Tasks;

    public class CommentsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ICommentService comments;

        public CommentsController(UserManager<User> userManager, ICommentService comments)
        {
            this.userManager = userManager;
            this.comments = comments;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(int postId, CommentBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(this.User);

            await this.comments.CreateAsync(userId, postId, model.Content);

            this.TempData.AddSuccessMessage("Comment succesfully posted!");

            return RedirectToAction("Details", "Posts", new { id = postId });
        }
    }
}

MyBlog.Web/Controllers/LikesController.cs
namespace MyBlog.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using MyBlog.Models;
    using Services.Contracts;
    using System.Threading.Tasks;

    public class LikesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ILikeService likes;

        public LikesController(ILikeService likes, UserManager<User> userManager)
        {
            this.userManager = userManager;
            this.likes = likes;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Like(int postId)
        {
            var userId = this.userManager.GetUserId(User);

            await this.likes.CreateAsync(postId, userId);

            return RedirectToAction("Details", "Posts", new { id = postId });
        }
    }
}

MyBlog.Web/Pages/Categories/Posts.cshtml.cs
namespace MyBlog.Web.Pages
{ 
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Common.ViewModels;
    using Services.Contracts;

    public class PostsModel : PageModel
    {
        private readonly ICategoryService categories;

        public PostsModel(ICategoryService categories)
        {
            this.categories = categories;
        }

        public IEnumerable<PostsByCategoryViewModel> Categories { get; set; }

        public void OnGet()
        {
            this.Categories = this.categories.CategoriesWithPosts();
        }
    }
}

MyBlog.Web/Pages/Posts/Archives.cshtml.cs
namespace MyBlog.Web.Pages.Posts
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using MyBlog.Common.ViewModels.Posts;
    using MyBlog.Models;
    using MyBlog.Services.Contracts;

    public class ArchivesModel : PageModel
    {
        private readonly IPostService posts;
        private readonly UserManager<User> userManager;

        public IEnumerable<PostArchiveViewModel> Archives { get; set; }

        public ArchivesModel(IPostService posts, UserManager<User> userManager)
        {
            this.posts = posts;
            this.userManager = userManager;
        }

        public void OnGet()
        {
            this.Archives = this.posts.Archives();

            Page();
        }
    }
}

MyBlog.Web/Pages/Posts/Details.cshtml.cs
namespace MyBlog.Web.Pages.Posts
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using MyBlog.Common.ViewModels.Posts;
    using MyBlog.Models;
    using MyBlog.Services.Contracts;

    public class DetailsModel : PageModel
    {
        private readonly IPostService posts;
        private readonly UserManager<User> userManager;

        public PostDetailsViewModel Post { get; set; }

        public DetailsModel(IPostService posts, UserManager<User> userManager)
        {
            this.posts = posts;
            this.userManager = userManager;
        }

        public IActionResult OnGet(int id)
        {
            this.Post = this.posts.Details(id);

            if (Post == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

MyBlog.Web/Pages/Posts/Archives.cshtml
@page
@model MyBlog.Web.Pages.Posts.ArchivesModel
@using System.Globalization
@{
    ViewData["Title"] = "Archives";
}

<h2>Archives</h2>
<hr />
@foreach (var item in Model.Archives)
{
    <h3>
        @CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(item.Month) @item.Year
    </h3>
    <ul>
        @foreach (var post in item.Posts)
        {
            <li>
                <a asp-area=""
                   asp-controller="Posts"
                   asp-action="Details"
                   asp-route-id="@post.Id">@post.Title</a>
            </li>
        }
    </ul>
    <hr />
}

MyBlog.Web/Pages/Posts/Details.cshtml
@page "id"
@model MyBlog.Web.Pages.Posts.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-9">
            <hr>
            <h2>@Model.Post.Title</h2>
            <h5><i class="far fa-clock"></i> Post by @Model.Post.Author, @Model.Post.PublishDate.ToString("D")</h5>
            <h5><span class="label label-primary">Category: @Model.Post.Category</span></h5><br>
            <p>@Model.Post.Content</p>
            @{
                var like = Model.Post.Likes.FirstOrDefault(l => l.PostId == Model.Post.Id && l.Username == this.User.Identity.Name);

                bool isLiked = false;

                if (like != null)
                {
                    isLiked = like.IsClicked;
                }
            }
            @if (!isLiked)
            {
                <form method="post">
                    <button asp-controller="Likes"
                            asp-action="Like"
                            asp-route-postId="@Model.Post.Id"
                            name="theButton" class="btn btn-primary">
                        <i class="fa fa-thumbs-up"></i><span> @Model.Post.Likes.Count(l => l.IsClicked) Likes</span>
                    </button>
                </form>
            }
            else
            {
                <button disabled name="theButton" class="btn btn-info">
                    <i class="fa fa-thumbs-up"></i><span> @Model.Post.Likes.Count(l => l.IsClicked) Likes</span>
                </button>
            }
            <br><br>
            <h4>Leave a Comment:</h4>
            <form method="post">
                <div class="form-group">
                    <textarea class="form-control" name="content" rows="3" required></textarea>
                </div>
                <input type="submit" asp-area="" asp-controller="Comments" asp-action="Create" asp-route-postId="@Model.Post.Id" class="btn btn-success"></>
            </form>
            <br><br>
            <h3>@Model.Post.Comments.Count() Comments:</h3><br>
            <partial name="_Comments" model="@Model.Post.Comments">
                </>
        </div>
    </div>
</div>