MyBlog.Web/Areas/Admin/Controllers/CategoriesController.cs
namespace MyBlog.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MyBlog.Common.BindingModels;
    using MyBlog.Web.Infrastructure.Extensions;
    using Services.Contracts;
    using System.Threading.Tasks;

    public class CategoriesController : AdminController
    {
        private readonly ICategoryService categories;

        public CategoriesController(ICategoryService categories)
        {
            this.categories = categories;
        }

        public IActionResult Index()
        {
            var model = this.categories.All();

            return View(model);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CategoryBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var success = await this.categories.CreateAsync(model.Name);

            if (!success)
            {
                this.ModelState.AddModelError("", "This category already exists!");

                return View();
            }

            this.TempData.AddSuccessMessage(string.Format(WebConstants.CreatedMessage, "Category"));

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var category = this.categories.ById(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CategoryBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            await this.categories.EditAsync(id, model);

            this.TempData.AddSuccessMessage(string.Format(WebConstants.EdittedMessage, "Category"));
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var category = this.categories.ById(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, CategoryBindingModel model)
        {
            await this.categories.DeleteAsync(id);

            this.TempData.AddSuccessMessage(string.Format(WebConstants.DeletedMessage, "Category"));

            return RedirectToAction("Index");
        }
    }
}

MyBlog.Web/Areas/Admin/Controllers/UsersController.cs
namespace MyBlog.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using MyBlog.Common.BindingModels;
    using MyBlog.Models;
    using MyBlog.Services.Contracts;
    using MyBlog.Web.Infrastructure.Extensions;
    using System.Threading.Tasks;

    public class UsersController : AdminController
    {
        private readonly UserManager<User> userManager;
        private readonly IUserService users;

        public UsersController(UserManager<User> userManager, IUserService users)
        {
            this.userManager = userManager;
            this.users = users;
        }

        public IActionResult Index()
        {
            var currentUserId = this.userManager.GetUserId(this.User);

            var model = this.users.All(currentUserId);

            return View(model);
        }

        public async Task<IActionResult> Delete(string username)
        {
            if (string.IsNullOrWhiteSpace(username))
            {
                return NotFound();
            }

            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            var model = new UserBindingModel
            {
                Username = username
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserBindingModel model)
        {
            var user = await this.userManager.FindByNameAsync(model.Username);

            await this.userManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }

        public IActionResult Ban(UserLockoutBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> BanAsync(UserLockoutBindingModel model)
        {
            var user = await this.userManager.FindByNameAsync(model.Username);

            await this.userManager.SetLockoutEndDateAsync(user, model.LockoutEnd);

            this.TempData.AddSuccessMessage($"User {user.UserName} successfully banned!");
            return RedirectToAction("Index");
        }

    }
}

MyBlog.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleBlog(Admin)</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/css/bootstrap.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">Simple Blog (Admin)</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Users" asp-action="Index">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Categories" asp-action="Index">Categories</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempDataSuccessMessageKey]
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SimpleBlog</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>